# Generated by Django 6.1 on 2026-08-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('shared', 'Shared'), ('self_contain', 'Self-Contain'), ('two_bedroom', '2-Bedroom Apartment')], max_length=15),
        ),
    ]
