# Generated by Django 6.1.1 on 2026-10-03 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office_hours', models.CharField(blank=True, max_length=100)),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='portal.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='BlockAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='portal.blocksupervisor')),
            ],
        ),
    ]
